/*Povoando tabela de setores com todos os setores da ctb*/
use gestaodecontratos;

insert into setor values ("09140000", "Companhia de Transportes do Estado da Bahia", "CTB");
insert into setor values ("09140174","Arquivo Central", "CTB/ ARQ CENTRAL");
insert into setor values ("09140190","Arquivo Corrente", "CTB/ ARQ CORRENTE");
insert into setor values ("09140204", "Diretoria de Presidencia", "CTB/ DIPRE");
insert into setor values ("09140212", "Assessoria Juridica", "CTB/ ASJUR");
insert into setor values ("09140220", "Assessoria Tecnica", "CTB/ ASTEC");
insert into setor values ("09140239", "Assessoria de Relacoes Institucionais", "CTB/ ASREI");
insert into setor values ("09140247", "Diretoria Administrativa e Financeira", "CTB/ DIRAF");
insert into setor values ("09140255", "Coordenadoria de Desenvolvimento da Gestao", "CTB/ CODGE");
insert into setor values ("09140263", "Subcoordenadoria de Gestao e Qualidade dos Servicos", "CTB/ QUAS");
insert into setor values ("09140271", "Subcoordenadoria de Tecnologia da Informação", "CTB/ TECI");
insert into setor values ("09140280", "Subcoordenadoria de Gestao de Pessoas", "CTB/ GESP");
insert into setor values ("09140298", "Coordenadoria Administrativa", "CTB/ COADM");
insert into setor values ("09140301", "Subcoordenadoria de Suprimentos e Patrimonio", "CTB/ SPAT");
insert into setor values ("09140310", "Subcoordenadoria de Gestao de Servicos", "CTB/ GSER");
insert into setor values ("09140328", "Coordenadoria Financeira", "CTB/ COFIN");
insert into setor values ("09140336", "Subcoordenadoria de Controle e Execucao Financeira", "CTB/ CEFI");
insert into setor values ("09140344", "Subcoordenadoria de Faturamento e Cobranca", "CTB/ FATC");
insert into setor values ("09140352", "Subcoordenadoria de Contabilidade", "CTB/ CONT");
insert into setor values ("09140360", "Subcoordenadoria de Convenios e Contratos", "CTB/ CONV");
insert into setor values ("09140409", "Diretoria de Operacao e Manutencao", "CTB/ DIROM");
insert into setor values ("09140417", "Coordenadoria de Manutencao", "CTB/ COMAN");
insert into setor values ("09140425", "Subcoordenadoria de Material Rodante", "CTB/ MARO");
insert into setor values ("09140433", "Subcoordenadoria de Sistema Fixo", "CTB/ SISF");
insert into setor values ("09140441", "Subcoordenadoria de Via Permanente", "CTB/ VIAP");
insert into setor values ("09140450", "Coordenadoria de Operacao", "CTB/ COOPE");
insert into setor values ("09140468", "Subcoordenadoria de Trens Controle e Movimento", "CTB/ TMOV");
insert into setor values ("09140476", "Subcoordenadoria de Planejamento Operacional das Estacoes", "CTB/ POPE");
insert into setor values ("09140484", "Diretoria das Estacoes", "CTB/ DIRES");
insert into setor values ("09140492", "Coordenadoria de Bem Estar do Usuario", "CTB/ COBEU");
insert into setor values ("09140506", "Subcoordenadoria de Seguranca dos Usuarios", "CTB/ SEGU");
insert into setor values ("09140514", "Coordenadoria de Seguranca", "CTB/ COSEG");
insert into setor values ("09140522", "Subcoordenadoria de Seguranca Patrimonial", "CTB/ SEPA");
insert into setor values ("09140530", "Diretoria de Planejamento", "CTB/ DIPLA");
insert into setor values ("09140549", "Coordenadoria de Avaliacao e Acompanhamento de Projetos", "CTB/ COAAP");
insert into setor values ("09140557", "Coordenadoria de Estudos e Planos", "CTB/ COESP");
insert into setor values ("09140565", "Diretoria de Obras", "CTB/ DIROB");
insert into setor values ("09140573", "Coordenadoria de Operacoes Especiais", "CTB/ COOES");
insert into setor values ("09140581", "Coordenadoria de Fiscalizacao de Obras", "CTB/ COFIS");

select * from setor;